{"name": "Всплывающее окно с деталями закрывается крестиком", "status": "broken", "statusDetails": {"message": "ValueError: response body:\n{\"message\":\"API rate limit exceeded for 93.158.188.79. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\",\"documentation_url\":\"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting\"}\n\nrequest url:\nhttps://api.github.com/repos/mozilla/geckodriver/releases/latest\nresponse headers:\n{'Date': 'Tue, 05 Mar 2024 11:52:21 GMT', 'Server': 'Varnish', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'deny', 'X-XSS-Protection': '1; mode=block', 'Content-Security-Policy': \"default-src 'none'; style-src 'unsafe-inline'\", 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-RateLimit-Used, X-RateLimit-Resource, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset', 'Content-Type': 'application/json; charset=utf-8', 'Referrer-Policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', 'X-GitHub-Media-Type': 'github.v3; format=json', 'X-RateLimit-Limit': '60', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1709640911', 'X-RateLimit-Resource': 'core', 'X-RateLimit-Used': '60', 'Content-Length': '279', 'X-GitHub-Request-Id': '086A:20ECCD:72055D7:72CDE0E:65E70775'}", "trace": "request = <SubRequest 'driver' for <Function test_click_to_x_closes_ingredient_popup[firefox]>>\n\n    @allure.step('Открываем браузер')\n    @pytest.fixture(params=['chrome', 'firefox'])\n    def driver(request):\n        if request.param == 'chrome':\n            service = Service(ChromeDriverManager().install())\n            driver = webdriver.Chrome(service=service)\n        elif request.param == 'firefox':\n>           service = Service(GeckoDriverManager().install())\n\nconftest.py:20: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/webdriver_manager/firefox.py:39: in install\n    driver_path = self._get_driver_binary_path(self.driver)\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/webdriver_manager/core/manager.py:35: in _get_driver_binary_path\n    binary_path = self._cache_manager.find_driver(driver)\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/webdriver_manager/core/driver_cache.py:105: in find_driver\n    driver_version = self.get_cache_key_driver_version(driver)\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/webdriver_manager/core/driver_cache.py:152: in get_cache_key_driver_version\n    return driver.get_driver_version_to_download()\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/webdriver_manager/core/driver.py:48: in get_driver_version_to_download\n    return self.get_latest_release_version()\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/webdriver_manager/drivers/firefox.py:29: in get_latest_release_version\n    resp = self._http_client.get(\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/webdriver_manager/core/http.py:36: in get\n    self.validate_response(resp)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresp = <Response [403]>\n\n    @staticmethod\n    def validate_response(resp: requests.Response):\n        status_code = resp.status_code\n        if status_code == 404:\n            raise ValueError(f\"There is no such driver by url {resp.url}\")\n        elif status_code == 401:\n            raise ValueError(f\"API Rate limit exceeded. You have to add GH_TOKEN!!!\")\n        elif resp.status_code != 200:\n>           raise ValueError(\n                f\"response body:\\n{resp.text}\\n\"\n                f\"request url:\\n{resp.request.url}\\n\"\n                f\"response headers:\\n{dict(resp.headers)}\\n\"\n            )\nE           ValueError: response body:\nE           {\"message\":\"API rate limit exceeded for 93.158.188.79. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\",\"documentation_url\":\"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting\"}\nE           \nE           request url:\nE           https://api.github.com/repos/mozilla/geckodriver/releases/latest\nE           response headers:\nE           {'Date': 'Tue, 05 Mar 2024 11:52:21 GMT', 'Server': 'Varnish', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'deny', 'X-XSS-Protection': '1; mode=block', 'Content-Security-Policy': \"default-src 'none'; style-src 'unsafe-inline'\", 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-RateLimit-Used, X-RateLimit-Resource, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset', 'Content-Type': 'application/json; charset=utf-8', 'Referrer-Policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', 'X-GitHub-Media-Type': 'github.v3; format=json', 'X-RateLimit-Limit': '60', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1709640911', 'X-RateLimit-Resource': 'core', 'X-RateLimit-Used': '60', 'Content-Length': '279', 'X-GitHub-Request-Id': '086A:20ECCD:72055D7:72CDE0E:65E70775'}\n\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/webdriver_manager/core/http.py:19: ValueError"}, "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1709639540566, "stop": 1709639540566, "uuid": "3fca045e-99fa-4653-a3f2-f7d88b096f91", "historyId": "6da7a6f46253168f1363a8a46acd6a0b", "testCaseId": "e221cc09a7c4d400807a6317073620fb", "fullName": "tests.test_main_page.TestMainFunctionality#test_click_to_x_closes_ingredient_popup", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_main_page"}, {"name": "subSuite", "value": "TestMainFunctionality"}, {"name": "host", "value": "sshapenkov-x"}, {"name": "thread", "value": "68203-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_main_page"}]}